name: Workflow for CI with github actions

on:
    push:
        branches:
            - master

env:
    baseUrl: http://localhost:3000


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Node
              uses: actions/setup-node@v4
              with:
                node-version: 20.x

            - name: Install Dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Checkout Typescript Errors
              run: npm i -g typescript && tsc
              
            - name: Checkout Eslint Errors
              run: npm run eslint

            - name: Lauch Unit Test && Integration Test
              run: npm run test

            - name: Save build data
              uses: actions/upload-artifact@v4
              with:
                name: build
                if-no-files-found: error
                path: .next # this is nextjs build path change it if .next is not default

            
    
    run-cypress-tests:
        runs-on: ubuntu-latest
        needs: build # need build job to process
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Download the build data
              uses: actions/download-artifact@v4
              with:
                name: build
                path: .next

            - name: Cypress run test
              uses: cypress-io/github-action@v6
              with:
                start: npm run start
                browser: chrome 

